name: XRefCheck

on: 
  push:
    branches:
      - review

jobs:
  crossref-check-without-anchors:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/XRefCheck.yml@main
    with:
      ignored-folders: 'Qualification/Input'
